import { Inter } from "next/font/google";
import Navbar from "./components/Navbar"
import TheCarousel from "./components/Carousel" 
import Card from './components/Card'
import Footer from './components/Footer'

import('bootstrap/dist/js/bootstrap.bundle.min.js');
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><Navbar/><TheCarousel/><Card/><Footer/>{children}</body>
    </html>
  );
}
